name: WebPage - RM

on: 
  push:
    branches:
      - master
      
jobs:
  publish:
    name: Publish GH Page
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Install deps
        if: success()
        run: npm install -f
      -
        name: Build
        if: success()
        run: npm run build
      -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}